pipeline {
    agent {
        node {
            label 'Agent-1'
            
        } 
    }
    environment { 
        GREETINGS = 'DEV'
    }

    stages {
        stage('clone code') {
            steps {
                echo "cloning the code"
            }
        }
        stage('build code') {
            steps {
                sh """
                    echo "HI im devops team"
                    env = $GREETINGS
                """
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the code"
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'SUCCESS'
        }
        failure { 
            echo 'FAILS'
        }
        aborted { 
            echo 'ABBORTED!'
        }
    }
}