pipeline {
    agent {
        node {
            label 'Agent-1'
            
        } 
    }
    environment { 
        GREETINGS = 'hello-jenkins'
    }
    options {
        timeout(time: 1, unit: 'HOURS') 
    }

    stages {
        stage('clone code') {
            steps {
                echo "cloning the code"
            }
        }
        stage('build code') {
            steps {
                sh """
                    echo "HI im devops team"
                    echo "$GREETINGS"
                """
            }
        }
        stage('Deploy') {
            steps {
                sh """
                    echo "Deploying"
                    sleep 10
                """
                
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
        }
        success { 
            echo 'SUCCESS'
        }
        failure { 
            echo 'FAILS'
        }
        aborted { 
            echo 'ABBORTED!'
        }
    }
}