pipeline {
    agent any 
    stages {
        stage('clone code') {
            steps {
                echo "cloning the code"
            }
        }
        stage('build code') {
            steps {
                echo "building the code"
            }
        }
        stage('Deploy') {
            steps {
                echo "Deploying the code"
            }
        }
    }
}